# Site settings
title: Augs Machado
description: A modern and elegant portfolio based in Jekyll template
keywords: Modern, Blogging, Fun, Portfolio, Programming
author: Augs Machado
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://augsmachado.github.io/" # the base hostname & protocol for your site
