# Site settings
title: Augs Machado
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun, Portfolio
author: Augs Machado
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://augsmachado.github.io/" # the base hostname & protocol for your site
